import { describe, expect, it } from 'vitest';
import { LARAVEL_EXTENSIONS, renderPhpIni } from '../php-ini';
import { backendFor } from '../index';

/**
 * These pin a finding from the P1 spike, not a doc claim.
 *
 * The Windows FrankenPHP archive is the official PHP binary distribution plus
 * `frankenphp.exe`, and that distribution ships NO active `php.ini` — only the
 * `-development` / `-production` templates. So a freshly extracted runtime loads
 * zero extensions: `php -m` shows `PDO` with no drivers and no `mbstring`,
 * `openssl`, `fileinfo` or `curl`. The spike's Laravel app rendered its own
 * error page and then died on the first query with
 * `could not find driver (Connection: sqlite)`.
 */
describe('renderPhpIni', () => {
    it('points PHP at the runtime ext/ directory with forward slashes', () => {
        const ini = renderPhpIni({ extensionDir: 'C:\\genie\\frankenphp\\ext' });
        expect(ini).toContain('extension_dir = "C:/genie/frankenphp/ext"');
    });

    it('enables the drivers a Laravel app dies without', () => {
        const ini = renderPhpIni({ extensionDir: '/opt/frankenphp/ext' });
        for (const ext of ['pdo_sqlite', 'pdo_mysql', 'mbstring', 'openssl', 'fileinfo']) {
            expect(ini).toContain(`extension = ${ext}`);
        }
    });

    it('never lists an extension that is already compiled in', () => {
        // Naming a built-in makes PHP warn on every single start, which turns
        // the runtime's own log into noise nobody reads.
        for (const builtin of ['json', 'ctype', 'tokenizer', 'pcre', 'session', 'bcmath']) {
            expect(LARAVEL_EXTENSIONS).not.toContain(builtin);
        }
    });

    it('accepts extra settings and a custom extension set', () => {
        const ini = renderPhpIni({
            extensionDir: '/x/ext',
            extensions: ['redis'],
            settings: { memory_limit: '512M' },
        });
        expect(ini).toContain('memory_limit = 512M');
        expect(ini).toContain('extension = redis');
        expect(ini).not.toContain('extension = pdo_mysql');
    });

    it('is a complete file — comment header and trailing newline', () => {
        const ini = renderPhpIni({ extensionDir: '/x/ext' });
        expect(ini.startsWith('; Generated by Genie')).toBe(true);
        expect(ini.endsWith('\n')).toBe(true);
    });
});

describe('backendFor', () => {
    it('serves a static site without needing FrankenPHP at all', () => {
        // The common case is a built frontend; requiring a ~60 MB PHP runtime to
        // preview one would be a download for nothing.
        expect(backendFor({ kind: 'static' }, { frankenphp: false })).toBe('static');
    });

    it('routes a php site to FrankenPHP when it is available', () => {
        expect(backendFor({ kind: 'php' }, { frankenphp: true })).toBe('frankenphp');
    });

    it('returns null for a php site with no runtime, rather than a doomed backend', () => {
        expect(backendFor({ kind: 'php' }, { frankenphp: false })).toBeNull();
    });
});
