import fs from 'node:fs/promises';
import path from 'node:path';
import { spawn } from 'node:child_process';
import { renderCaddyfile } from './caddyfile';
import { renderPhpIni } from './php-ini';
import { assignPort, hostedOrigin } from './ports';
import type {
    ConfigWriter,
    HostedProcessHandle,
    HostedSite,
    HostedStatus,
    ProcessSpawner,
    SiteRuntime,
    SpawnOptions,
} from './types';

/**
 * The FrankenPHP {@link SiteRuntime} adapter — Genie's cross-platform answer to
 * "PHP + web server + valid local TLS", the hardest part of Herd to reproduce on
 * three operating systems.
 *
 * FrankenPHP collapses all three into one artifact (embedded PHP + Caddy +
 * automatic TLS), and as of v1.12 it runs NATIVELY on Windows as well as macOS
 * and Linux — so one adapter covers every platform Genie ships to.
 *
 * ONE PROCESS PER SITE. FrankenPHP could serve every site from a single process
 * (one Caddyfile with many site blocks), which would save memory — each instance
 * embeds a PHP interpreter and starts 2×CPU threads. We take a process per site
 * anyway in P1 because the contract here is per-site start/stop/status: a shared
 * process turns "stop one site" into a config reload that can fail and take the
 * other sites with it, and it makes one app's crash everyone's outage. Revisit
 * when the site count per workspace makes memory the binding constraint.
 *
 * THIN IMPURE. The Caddyfile itself is generated by the pure `caddyfile.ts`, the
 * port by the pure `ports.ts`; everything left here is spawn + write, both
 * injected, so the whole lifecycle is unit-tested with no binary on the machine.
 */

// --- readiness -------------------------------------------------------------

/**
 * Caddy's own "I am up" line, emitted on stderr once the config is live.
 *
 * Readiness has to be OBSERVED, not assumed. The process existing means nothing
 * — an invalid Caddyfile, a port already taken or a bad document root all
 * produce a process that lives just long enough to exit non-zero. Reporting
 * `running` on spawn would hand the Testing Browser a target that refuses every
 * connection, which is exactly the class of failure this whole runtime exists to
 * remove. Verified against FrankenPHP 1.12.6 / Caddy 2.11.4.
 */
export const READY_MARKER = 'serving initial configuration';

/** How long a site gets to come up before we call it failed and kill it. */
export const START_TIMEOUT_MS = 20_000;

/** Keep the stderr tail bounded — it only exists to explain a failure. */
const STDERR_TAIL_LIMIT = 4_000;

// --- default seams ---------------------------------------------------------

const defaultSpawner: ProcessSpawner = {
    spawn(command: string, args: string[], opts: SpawnOptions): HostedProcessHandle {
        // Never `shell: true` (argv injection); always `windowsHide` — a hosted
        // site must not flash a console window on Windows.
        const child = spawn(command, args, {
            cwd: opts.cwd,
            env: { ...process.env, ...opts.env },
            shell: false,
            windowsHide: true,
            stdio: ['ignore', 'pipe', 'pipe'],
        });
        child.stderr?.on('data', (chunk) => opts.onStderr?.(String(chunk)));
        // Caddy logs to stderr, but a PHP fatal can land on stdout — surface both.
        child.stdout?.on('data', (chunk) => opts.onStderr?.(String(chunk)));
        const exited = new Promise<number | null>((resolve) => {
            child.on('error', () => resolve(null));
            child.on('close', (code) => resolve(code));
        });
        return {
            get pid() {
                return child.pid;
            },
            exited,
            stop() {
                try {
                    child.kill();
                } catch {
                    /* already gone */
                }
            },
        };
    },
};

const defaultWriter: ConfigWriter = {
    async write(filePath: string, contents: string) {
        await fs.mkdir(path.dirname(filePath), { recursive: true });
        await fs.writeFile(filePath, contents, 'utf8');
    },
};

// --- runtime ---------------------------------------------------------------

export interface FrankenPhpRuntimeOptions {
    /** Absolute path to `frankenphp` / `frankenphp.exe`. */
    binaryPath: string;
    /** Where generated Caddyfiles and Caddy's persistent state live — Genie's
     *  userData dir. Must persist: it holds the local CA root. */
    stateDir: string;
    spawner?: ProcessSpawner;
    writer?: ConfigWriter;
    /** See `CaddyfileOptions.skipInstallTrust` — defaults to skipping. */
    skipInstallTrust?: boolean;
    /** Overrides {@link extensionDirFor}, for a runtime laid out differently. */
    extensionDir?: string;
    /** Overrides {@link LARAVEL_EXTENSIONS}. */
    extensions?: readonly string[];
    startTimeoutMs?: number;
}

interface Entry {
    status: HostedStatus;
    proc?: HostedProcessHandle;
    stderr: string;
    /** Set by `stop()` so the resulting exit is not reported as a crash. */
    stopping?: boolean;
}

/** Where one site's generated config lives. Named `Caddyfile` so the base name
 *  alone identifies the adapter, and per-site so configs never collide. */
export function siteConfigPath(stateDir: string, siteId: string): string {
    return path.join(stateDir, 'sites', siteId, 'Caddyfile');
}

/** Where the generated ini goes. Its DIRECTORY is what `PHP_INI_SCAN_DIR` gets —
 *  PHP scans a directory, not a file. Shared by every site: the extension set is
 *  a property of the runtime, not of one app. */
export function phpIniDir(stateDir: string): string {
    return path.join(stateDir, 'php-ini.d');
}

/** `ext/` inside an extracted FrankenPHP, derived from the binary's location. */
export function extensionDirFor(binaryPath: string): string {
    return path.join(path.dirname(binaryPath), 'ext');
}

/** The argv FrankenPHP is started with. Exported so the test pins it exactly. */
export function runArgs(configPath: string): string[] {
    return ['run', '--config', configPath, '--adapter', 'caddyfile'];
}

export function createFrankenPhpRuntime(opts: FrankenPhpRuntimeOptions): SiteRuntime {
    const spawner = opts.spawner ?? defaultSpawner;
    const writer = opts.writer ?? defaultWriter;
    const startTimeoutMs = opts.startTimeoutMs ?? START_TIMEOUT_MS;
    const entries = new Map<string, Entry>();

    const stopped = (siteId: string): HostedStatus => ({
        siteId,
        state: 'stopped',
        backend: 'frankenphp',
        target: null,
        origin: null,
    });

    const takenPorts = (): Set<number> => {
        const taken = new Set<number>();
        for (const entry of entries.values()) {
            const port = entry.status.target?.port;
            if (port !== undefined) taken.add(port);
        }
        return taken;
    };

    async function start(site: HostedSite): Promise<HostedStatus> {
        const existing = entries.get(site.id);
        // Idempotent — re-starting a live site must not orphan its process.
        if (existing && (existing.status.state === 'running' || existing.status.state === 'starting')) {
            return existing.status;
        }

        const port = assignPort(site.id, takenPorts());
        const configPath = siteConfigPath(opts.stateDir, site.id);
        const caddyfile = renderCaddyfile(site, {
            port,
            storageDir: path.join(opts.stateDir, 'caddy'),
            skipInstallTrust: opts.skipInstallTrust,
        });
        await writer.write(configPath, caddyfile);

        // The archive ships no active php.ini, so without this a Laravel app
        // boots with no PDO driver and no mbstring — see `php-ini.ts`.
        const iniDir = phpIniDir(opts.stateDir);
        await writer.write(
            path.join(iniDir, 'genie.ini'),
            renderPhpIni({
                extensionDir: opts.extensionDir ?? extensionDirFor(opts.binaryPath),
                extensions: opts.extensions,
            }),
        );

        const entry: Entry = {
            status: {
                siteId: site.id,
                state: 'starting',
                backend: 'frankenphp',
                target: null,
                origin: null,
            },
            stderr: '',
        };
        entries.set(site.id, entry);

        const ready = new Promise<HostedStatus>((resolve) => {
            let settled = false;
            const timer = setTimeout(() => {
                finish('failed', `did not report ready within ${startTimeoutMs}ms`);
                entry.proc?.stop();
            }, startTimeoutMs);

            const finish = (state: 'running' | 'failed', error?: string) => {
                if (settled) return;
                settled = true;
                clearTimeout(timer);
                if (state === 'running') {
                    entry.status = {
                        siteId: site.id,
                        state: 'running',
                        backend: 'frankenphp',
                        target: {
                            scheme: 'https',
                            hostname: site.hostname.toLowerCase(),
                            port,
                            loopback: '127.0.0.1',
                        },
                        origin: hostedOrigin(site.hostname, port, 'https'),
                        pid: entry.proc?.pid,
                    };
                } else {
                    entry.status = { ...stopped(site.id), state: 'failed', error };
                }
                resolve(entry.status);
            };

            entry.proc = spawner.spawn(opts.binaryPath, runArgs(configPath), {
                // cwd is the document root so any relative path in the app (or in
                // a worker `watch` pattern) resolves the way the app expects.
                cwd: site.root,
                env: { PHP_INI_SCAN_DIR: iniDir },
                onStderr: (chunk) => {
                    entry.stderr = (entry.stderr + chunk).slice(-STDERR_TAIL_LIMIT);
                    if (chunk.includes(READY_MARKER)) finish('running');
                },
            });

            void entry.proc.exited.then((code) => {
                // A stop WE asked for is not a crash. Without this, stopping a
                // site that is still STARTING resolves its pending `start()` as
                // `failed` with a spurious "frankenphp exited" error — the
                // caller is told the site crashed when it did exactly what it
                // was told to do.
                if (entry.stopping) {
                    finish('failed', 'stopped before it finished starting');
                    return;
                }
                // An exit BEFORE ready is a start failure; after ready it is a
                // crash. Either way the site is no longer serving.
                const error = `frankenphp exited (${code}): ${entry.stderr.slice(-500)}`;
                finish('failed', error);
                if (entry.status.state === 'running') {
                    entry.status = { ...stopped(site.id), state: 'failed', error };
                }
            });
        });

        return ready;
    }

    async function stop(siteId: string): Promise<void> {
        const entry = entries.get(siteId);
        if (!entry) return;
        entry.stopping = true;
        entry.proc?.stop();
        if (entry.proc) await entry.proc.exited;
        entries.delete(siteId);
    }

    return {
        backend: 'frankenphp',
        start,
        stop,
        status: (siteId) => entries.get(siteId)?.status ?? stopped(siteId),
        list: () => [...entries.values()].map((e) => e.status),
        async stopAll() {
            await Promise.all([...entries.keys()].map((id) => stop(id)));
        },
    };
}
