/**
 * PURE `php.ini` generation for the FrankenPHP adapter.
 *
 * This file exists because of a finding from the P1 spike, not from the docs.
 *
 * The Windows FrankenPHP archive is the official PHP binary distribution plus
 * `frankenphp.exe`. That distribution ships every extension as a DLL in `ext/`
 * but ships NO ACTIVE `php.ini` — only `php.ini-development` / `php.ini-production`
 * templates. So a freshly extracted FrankenPHP loads **zero** extensions:
 * no `mbstring`, no `openssl`, no `fileinfo`, no `curl`, and `PDO` with no
 * drivers at all.
 *
 * A Laravel app on that PHP boots far enough to render its own error page and
 * then dies on the first database call — the spike hit exactly that
 * (`could not find driver (Connection: sqlite)`) and the site looked "hosted but
 * broken". Genie therefore has to generate an ini itself; it cannot rely on the
 * archive being usable as shipped.
 *
 * The mechanism is `PHP_INI_SCAN_DIR`, pointed at a directory Genie owns. That
 * is additive and leaves the extracted runtime untouched, so an upgrade can
 * replace the whole FrankenPHP directory without losing configuration.
 */

/** Extensions a Laravel app needs that the archive does not enable by default.
 *
 *  `ctype`, `json`, `tokenizer`, `dom`/`xml`, `filter`, `hash`, `pcre`, `session`
 *  and `bcmath` are already compiled IN on Windows, so they are deliberately
 *  absent here — listing a built-in extension makes PHP warn on every start. */
export const LARAVEL_EXTENSIONS = [
    'curl',
    'fileinfo',
    'intl',
    'mbstring',
    'openssl',
    'pdo_mysql',
    'pdo_pgsql',
    'pdo_sqlite',
    'sqlite3',
    'zip',
] as const;

export interface PhpIniOptions {
    /** ABSOLUTE path to the runtime's `ext/` directory. */
    extensionDir: string;
    /** Defaults to {@link LARAVEL_EXTENSIONS}. */
    extensions?: readonly string[];
    /** Extra raw `key = value` settings (e.g. `memory_limit`). */
    settings?: Record<string, string>;
}

/**
 * Render the ini Genie drops into its `PHP_INI_SCAN_DIR`.
 *
 * Paths are normalised to forward slashes — PHP accepts them on Windows, and it
 * keeps the file free of backslash-escaping questions.
 */
export function renderPhpIni(opts: PhpIniOptions): string {
    const lines = [
        '; Generated by Genie. Do not edit — rewritten on every site start.',
        `extension_dir = "${opts.extensionDir.replace(/\\/g, '/')}"`,
    ];
    for (const [key, value] of Object.entries(opts.settings ?? {})) {
        lines.push(`${key} = ${value}`);
    }
    for (const ext of opts.extensions ?? LARAVEL_EXTENSIONS) {
        lines.push(`extension = ${ext}`);
    }
    return `${lines.join('\n')}\n`;
}
