import fs from 'node:fs';
import path from 'node:path';
import { describe, expect, it } from 'vitest';
import {
    FEATURE_SURFACES,
    entryPointsInSource,
    unreachableFeatures,
    type FeatureSurface,
} from '../feature-reachability';

/**
 * NO FEATURE BECOMES UNREACHABLE — the guard behind "0 features lost".
 *
 * The Genie 2 plan deletes eight title-bar icons on the promise that those features
 * "survive as ⌘K entries". Measured 2026-10-05, that promise did not hold:
 *
 * - every feature is reached through an `onShow*` prop on the title bar
 *   (`master.tsx:4316-4515`), and
 * - the command palette (`GenieCommandWindow`, Tynn #247) exists but opens only
 *   "while a terminal panel has focus" (`master.tsx:3086`) — under the Deck no terminal
 *   is focused — and its items are workspaces, terminals and prompts, with NO feature
 *   entries at all.
 *
 * So deleting the icons first would have orphaned Sharing, Sites, IssueWatch, Flows,
 * AppStore and Knowledge. This file turns "0 features lost" from a sentence in a plan
 * into something CI refuses to let us break.
 *
 * `FEATURE_SURFACES` is the CONTRACT: a human has to consciously edit it to drop a
 * feature. The entry points are DISCOVERED by reading the real source, so the two cannot
 * drift into agreeing with each other.
 */

const ROOT = path.resolve(__dirname, '..', '..', '..');

/** CRLF-normalised: genie#517 is this repo's source guards going inert on `\r\n`, and
 *  `renderer/pages/master.tsx` is a CRLF file — verified, not assumed. */
function read(rel: string): string {
    return fs.readFileSync(path.join(ROOT, rel), 'utf8').replace(/\r\n/g, '\n');
}

const masterSrc = read('renderer/pages/master.tsx');
const paletteSrc = read('renderer/components/Master/GenieCommandWindow.tsx');

/**
 * Palette coverage is REAL only if the palette is wired to the contract in source.
 *
 * Feature entries are generated by `featureCommandItems(FEATURE_SURFACES)` rather than
 * written out one by one, so there is no literal `featureId: '...'` to scan for. Deriving
 * coverage from the contract alone would be circular -- it would claim every feature is in
 * the palette whether or not the palette renders any. So the wiring is source-checked, and
 * only then does the contract stand in for the ids.
 */
const paletteWiredToContract = /featureCommandItems\(\s*FEATURE_SURFACES\s*\)/.test(paletteSrc);

const foundEntryPoints = () => ({
    titleBarProps: entryPointsInSource(masterSrc).titleBarProps,
    paletteIds: new Set(paletteWiredToContract ? FEATURE_SURFACES.map((f) => f.id) : []),
});

describe('the guard reads the real thing (positive control)', () => {
    it('finds the file and it is not empty', () => {
        // Without this, every assertion below would also pass against an empty string.
        expect(masterSrc.length).toBeGreaterThan(50_000);
        expect(masterSrc).toContain('GenieCommandWindow');
    });

    it('normalises CRLF, so the guard cannot silently stop guarding', () => {
        const raw = fs.readFileSync(path.join(ROOT, 'renderer/pages/master.tsx'), 'utf8');
        // Proves the file really is CRLF — so the normalisation above is load-bearing
        // rather than decorative. If this ever flips to LF the guard still works; the
        // point is that it works EITHER way.
        expect(raw.includes('\r\n') || !raw.includes('\r')).toBe(true);
        expect(masterSrc).not.toContain('\r');
    });
});

describe('every contracted feature is reachable', () => {
    it('has no orphans', () => {
        const found = foundEntryPoints();
        const orphans = unreachableFeatures(FEATURE_SURFACES, found);
        // The message matters more than the assertion: whoever breaks this needs to know
        // WHICH feature they just stranded.
        expect(
            orphans.map((f) => `${f.label} (expected ${JSON.stringify(f.entry)})`),
            'these features have no reachable entry point',
        ).toEqual([]);
    });

    it('the contract is not empty, and covers the features the owner named', () => {
        // A guard over an empty list passes forever. Name the ones that matter.
        const ids = FEATURE_SURFACES.map((f) => f.id);
        expect(ids).toContain('remote-host');
        expect(ids).toContain('plugins-appstore');
        expect(ids).toContain('knowledge-graph');
        expect(ids).toContain('agent-inbox');
        expect(FEATURE_SURFACES.length).toBeGreaterThanOrEqual(12);
    });
});

describe('unreachableFeatures', () => {
    const found = { titleBarProps: new Set(['onShowKnowledge']), paletteIds: new Set(['hosts']) };

    it('accepts a feature whose title-bar prop is present', () => {
        const f: FeatureSurface = { id: 'k', label: 'Knowledge', entry: { titleBarProp: 'onShowKnowledge' } };
        expect(unreachableFeatures([f], found)).toEqual([]);
    });

    it('accepts a feature whose PALETTE entry is present, even with no icon', () => {
        // This is the whole point of P7: an icon may go away IF the palette carries it.
        const f: FeatureSurface = { id: 'h', label: 'Hosts', entry: { paletteId: 'hosts' } };
        expect(unreachableFeatures([f], found)).toEqual([]);
    });

    it('REPORTS a feature whose only entry point has been deleted', () => {
        const f: FeatureSurface = { id: 'x', label: 'Sharing', entry: { titleBarProp: 'onShowSharing' } };
        expect(unreachableFeatures([f], found).map((o) => o.id)).toEqual(['x']);
    });

    it('does NOT accept a contextual claim on its own', () => {
        // "You can still get there from the workspace row" is a promise a test cannot
        // check. Accepting it would make the guard a rubber stamp: anyone deleting an
        // icon could add `contextual` and go green. It must be paired with something real.
        const f: FeatureSurface = { id: 'c', label: 'Sites', entry: { contextual: 'workspace row' } };
        expect(unreachableFeatures([f], found).map((o) => o.id)).toEqual(['c']);
    });
});

describe('entryPointsInSource', () => {
    it('picks up the onShow* props that actually exist today', () => {
        const found = entryPointsInSource(masterSrc);
        expect(found.titleBarProps.has('onShowKnowledge')).toBe(true);
        expect(found.titleBarProps.has('onShowAppStore')).toBe(true);
        expect(found.titleBarProps.has('onShowAgentInbox')).toBe(true);
    });

    it('does not invent a prop that is not there', () => {
        // Discriminates a real scan from one that returns everything it was asked about.
        const found = entryPointsInSource(masterSrc);
        expect(found.titleBarProps.has('onShowSomethingNobodyBuilt')).toBe(false);
    });

    it('records the palette as carrying NO feature entries today', () => {
        // The measured fact that makes P7 unsafe right now. When the palette is widened
        // this assertion is the one that should be updated — deliberately.
        const found = entryPointsInSource(masterSrc);
        expect(found.paletteIds.size).toBe(0);
    });
});

describe('the palette is reachable without a terminal (the P7 precondition)', () => {
    it('is wired to the reachability contract, so every contracted feature is in it', () => {
        // Without this, deleting a title-bar icon would strand its feature even though the
        // plan says the palette carries it.
        expect(paletteWiredToContract).toBe(true);
    });

    it('does NOT derive its open state from a terminal id', () => {
        // The exact regression. `open={commandWindowFor !== null}` made a terminal id double
        // as the open flag, so the palette could not open on the Deck -- which focuses no
        // terminal -- and ⌘K would have done nothing at all.
        expect(masterSrc).not.toMatch(/open=\{commandWindowFor !== null\}/);
        expect(masterSrc).toMatch(/open=\{paletteOpen\}/);
    });

    it('acts on the global palette intent', () => {
        // `resolveShortcut` has always returned this intent; for a while nothing consumed
        // it, which is a resolved-and-ignored shortcut — a silent no-op.
        expect(masterSrc).toMatch(/intent\.kind === 'palette'/);
    });

    it('drops entries that cannot act, rather than showing them dead', () => {
        expect(paletteSrc).toContain('dropUndeliverable');
    });

    it('positive control: the palette source was really read', () => {
        expect(paletteSrc).toContain('GenieCommandWindowProps');
        expect(paletteSrc.length).toBeGreaterThan(3_000);
    });
});

/**
 * A PALETTE ROW THAT DOES NOTHING IS WORSE THAN NO ROW.
 *
 * `featureCommandItems(FEATURE_SURFACES)` generates a row for every contracted feature,
 * and `onActivateFeature` dispatches on `featureId` through a `switch` in master.tsx. A
 * `switch` with no matching `case` falls through SILENTLY — so adding a feature to the
 * contract makes a row appear whether or not anything happens when it is chosen.
 *
 * That is the failure the palette-coverage check above cannot see: it asks whether the
 * palette is wired to the contract, which is true for every id at once. This asks the
 * per-id question — does choosing this row DO anything — and the module's own reasoning
 * demands it: *"a dead row is worse than an absent one, the same reason a disabled control
 * is an accusation while a different shape is a fact."*
 *
 * Found while checking why `?view=grid` was the only route back to the Floor grid.
 */
describe('every contracted feature actually does something when chosen', () => {
    it('has a `case` in the onActivateFeature switch for every id', () => {
        const unhandled = FEATURE_SURFACES.filter(
            (f) => !new RegExp(`case '${f.id}':`).test(masterSrc),
        ).map((f) => `${f.id} (${f.label})`);
        expect(
            unhandled,
            'contracted features whose palette row would silently no-op',
        ).toEqual([]);
    });

    it('positive control: the case-scan really matches this file’s style', () => {
        // Without this, a change to how the switch is written (a map, an if-chain) would
        // make the assertion above vacuously green for EVERY feature at once.
        expect(masterSrc).toMatch(/case 'knowledge-graph':/);
        expect(masterSrc).toMatch(/onActivateFeature=\{/);
    });
});
